@@startuml

abstract class Player {
    - name: String
    - deck: Deck
    - hand: Hand
    - graveyard: Graveyard
    - board: Board
    - deckSize: Integer
    - handSize: Integer
    - graveyardSize: Integer
    - boardSize: Integer
    + draw()
    + play()
    + discard()
    + pass()
}

abstract class Card {
    - name: String
    - description: String
}

abstract class UnitCard {
    - power: Integer
    - faction : String
    - ability()
}

abstract class Spell{
    - ability()
}

abstract class Deck{
    - faction : String 
    - cards: CardList
}

abstract class CardList{
    
}

Card --> UnitCard : may be
Card --> Spell : may be
CardList --> Card : store
Deck --> Player : belongs

@@enduml
