@@startuml

class Human {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - is_stunned : bool
    - MAX_NAME_SIZE const : int
    + Human()
    + getName() const : string
    + getAge() const : int
    + getIs_stunned() const : bool
    + getCoins() const : double
    + getHealth() const : int
    + getStamina() const : int
    + setName() : void
    + setAge() : void
    + setCoins() : void
    + setHealth() : void
    + setStamina() : void
    + setIs_stunned() : void
    + print_info() const : void
    + talk() : void
    + walk() : void
}

class Ghoul {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - is_stunned : bool
    - MAX_NAME_SIZE const : int
    - GHOUL_ATTACK_COST const : int
    - MAX_GHOUL_DAMAGE const : int
    - MIN_GHOUL_DAMAGE const : int
    + Ghoul()
    + getName() const : string
    + getAge() const : int
    + getIs_stunned() const : bool
    + getCoins() const : double
    + getHealth() const : int
    + getStamina() const : int
    + setName() : void
    + setAge() : void
    + setCoins() : void
    + setHealth() : void
    + setStamina() : void
    + setIs_stunned() : void
    + attack() : void
    + print_info() const : void
    + talk() : void
    + walk() : void
}


@@enduml