@@startuml

abstract class Entity {
    - name : string
    - health : int
    - stamina : int
    - coins : double
    - is_stunned : bool
    - xp_level : int
    - category : string
    - global_level static : int
    - all_categorys const static: string[]
    - MAX_NAME_SIZE const : int
    + Entity()
    + print_info() const : void
    + talk() : void
    + walk() : void
}

class Human {
    + Human()
    + sell_items() : void
}

class Witcher {
    - school : WitcherSchool
    - sign : Sign
    - weapon : Weapon
    - armor : Armor
    - potions : Potion[]
    + Witcher()
    + attack(Entity &) : void
}

class Player {
    - xp_level static : int
    + interact() : void
}


abstract class Monster {
    - global_monster_level static : int
    - category : string
    + Monster()
    + attack(Entity &) : void
    + setGlobal_level() static : void
}

class Ghoul {
    - category : string
    - level : int
    + Ghoul()
    + attack(Entity &) : void
}

Entity <|-- Human
Entity <|-- Monster
Ghoul --|> Monster
Human <|-- Witcher
Player --|> Witcher

@@enduml