@@startuml


class Human {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - category : string
    - level : int
    - is_stunned : bool
    - CATEGORIES[] : string[]
    - MAX_NAME_SIZE const : int
    + Human()
    + print_info() const : void
    + talk() : void
    + walk() : void
}


class Ghoul {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - category : string
    - level : int
    - is_stunned : bool
    - CATEGORIES[] : string[]
    - MAX_NAME_SIZE const : int
    - GHOUL_ATTACK_COST const : int
    - MAX_GHOUL_DAMAGE const : int
    - MIN_GHOUL_DAMAGE const : int
    + Ghoul()
    + attack(Human &) : void
    + print_info() const : void
    + talk() : void
    + walk() : void
}


class Battle {
    - MAX_ALLIES const static : int
    - MAX_ENEMIES const static : int
    - allies[] : Human*
    - enemies[] : Ghoul*
    + Battle(Human&, Ghoul&)
    + getAlllies() const : void
    + getEnemies() const : void
    + addAllies(Human&) : void
    + addEnemies(Ghoul&) : void
    + checkAllies() : bool
    + checkEnemies() : bool
    + beginBattle() : void 
}


@@enduml