@@startuml


class Human {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - is_stunned : bool
    - MAX_NAME_SIZE const : int
    + Human()
    + print_info() const : void
    + talk() : void
    + walk() : void
}


class Ghoul {
    - name : string
    - age : int
    - coins : double
    - health : int
    - stamina : int
    - is_stunned : bool
    - MAX_NAME_SIZE const : int
    - GHOUL_ATTACK_COST const : int
    - MAX_GHOUL_DAMAGE const : int
    - MIN_GHOUL_DAMAGE const : int
    + Ghoul()
    + attack() : void
    + print_info() const : void
    + talk() : void
    + walk() : void
}


class Battle {
    - MAX_VICTIMS const static : int
    - MAX_ATTACKERS const static : int
    - victims[] : Human*
    - attackers[] : Ghoul*
    + Battle(Human&, Ghoul&)
}


@@enduml